COMMAND_PREFIX = "!"

LOADED_EXTENSIONS = ["repeatCog", "twitterCog", "twitchCog"]

DISCORD_BOT_TOKEN = ''

ANNONCE_CHANNEL_ID = 438626370180874242
ANNONCE_CHANNEL_TWITCH_ID = 445907885755727872

TWITCH_API_KEY = ""
TWITCH_APP_SECRET = ""
TWITCH_CHANNELS = [61859671]

GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
GOOGLE_SPREADSHEET_ID = ""

TWITTER_CONSUMER_KEY = ""
TWITTER_CONSUMER_SECRET = ""
TWITTER_ACCESS_TOKEN = ""
TWITTER_ACCESS_TOKEN_SECRET = ""
TWITTER_ACCOUNTS = ["JVlemag"]
